[package]
name = "day09"
authors.workspace = true
description.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
aoc_libs.workspace = true
regex.workspace = true
once_cell.workspace = true
